version: '3.8'

services:
    app:
        build:
            context: ./php
            dockerfile: Dockerfile
        container_name: app
        volumes:
           - ./:/var/www
        networks:
            - app-network
        command: bash -c "composer install && php-fpm"

    webserver:
        image: nginx:latest
        container_name: nginx-server
        ports:
            - "80:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/
        networks:
            - app-network
        depends_on:
            - app

    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=$(DB_DATABASE}
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    db_data:
